sonar.projectKey=hobsojam_SAFe_tooling
sonar.organization=hobsojam

sonar.projectName=SAFe_tooling

sonar.sources=safe,frontend/src
sonar.exclusions=tests/**,frontend/dist/**,frontend/coverage/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.javascript.lcov.reportPaths=coverage-frontend/lcov.info
