sonar.projectKey=hobsojam_SAFe_tooling
sonar.organization=hobsojam

sonar.projectName=SAFe_tooling

sonar.sources=safe
sonar.exclusions=tests/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage/coverage.xml
